/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as LienHeRouteImport } from './routes/lien-he'
import { Route as LinhVucRouteImport } from './routes/linh-vuc'
import { Route as PhuongThucRouteImport } from './routes/phuong-thuc'
import { Route as TinTucRouteImport } from './routes/tin-tuc'
import { Route as TinTucSlugRouteImport } from './routes/tin-tuc.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const LienHeRoute = LienHeRouteImport.update({
  id: '/lien-he',
  path: '/lien-he',
  getParentRoute: () => rootRouteImport,
} as any)
const LinhVucRoute = LinhVucRouteImport.update({
  id: '/linh-vuc',
  path: '/linh-vuc',
  getParentRoute: () => rootRouteImport,
} as any)
const PhuongThucRoute = PhuongThucRouteImport.update({
  id: '/phuong-thuc',
  path: '/phuong-thuc',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucRoute = TinTucRouteImport.update({
  id: '/tin-tuc',
  path: '/tin-tuc',
  getParentRoute: () => rootRouteImport,
} as any)
const TinTucSlugRoute = TinTucSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TinTucRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/linh-vuc': typeof LinhVucRoute
  '/phuong-thuc': typeof PhuongThucRoute
  '/tin-tuc': typeof TinTucRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/linh-vuc': typeof LinhVucRoute
  '/phuong-thuc': typeof PhuongThucRoute
  '/tin-tuc': typeof TinTucRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lien-he': typeof LienHeRoute
  '/linh-vuc': typeof LinhVucRoute
  '/phuong-thuc': typeof PhuongThucRoute
  '/tin-tuc': typeof TinTucRouteWithChildren
  '/tin-tuc/$slug': typeof TinTucSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/linh-vuc'
    | '/phuong-thuc'
    | '/tin-tuc'
    | '/tin-tuc/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/linh-vuc'
    | '/phuong-thuc'
    | '/tin-tuc'
    | '/tin-tuc/$slug'
  id:
    | '__root__'
    | '/'
    | '/gioi-thieu'
    | '/lien-he'
    | '/linh-vuc'
    | '/phuong-thuc'
    | '/tin-tuc'
    | '/tin-tuc/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LienHeRoute: typeof LienHeRoute
  LinhVucRoute: typeof LinhVucRoute
  PhuongThucRoute: typeof PhuongThucRoute
  TinTucRoute: typeof TinTucRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lien-he': {
      id: '/lien-he'
      path: '/lien-he'
      fullPath: '/lien-he'
      preLoaderRoute: typeof LienHeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/linh-vuc': {
      id: '/linh-vuc'
      path: '/linh-vuc'
      fullPath: '/linh-vuc'
      preLoaderRoute: typeof LinhVucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/phuong-thuc': {
      id: '/phuong-thuc'
      path: '/phuong-thuc'
      fullPath: '/phuong-thuc'
      preLoaderRoute: typeof PhuongThucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc': {
      id: '/tin-tuc'
      path: '/tin-tuc'
      fullPath: '/tin-tuc'
      preLoaderRoute: typeof TinTucRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tin-tuc/$slug': {
      id: '/tin-tuc/$slug'
      path: '/$slug'
      fullPath: '/tin-tuc/$slug'
      preLoaderRoute: typeof TinTucSlugRouteImport
      parentRoute: typeof TinTucRoute
    }
  }
}

interface TinTucRouteChildren {
  TinTucSlugRoute: typeof TinTucSlugRoute
}

const TinTucRouteChildren: TinTucRouteChildren = {
  TinTucSlugRoute: TinTucSlugRoute,
}

const TinTucRouteWithChildren =
  TinTucRoute._addFileChildren(TinTucRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GioiThieuRoute: GioiThieuRoute,
  LienHeRoute: LienHeRoute,
  LinhVucRoute: LinhVucRoute,
  PhuongThucRoute: PhuongThucRoute,
  TinTucRoute: TinTucRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
